name: credimi-tests test
on:
  pull_request:
    branches:
      - main

jobs:
  credimi:
    runs-on: ubuntu-latest
    name: 🧪 Test a pipeline using remote EUDIW wallet
    steps:
      - name: 🛎️  Checkout
        uses: actions/checkout@v6
      - name: 🧪 Run the wallet pipeline
        uses: ./
        with:
          api-key: ${{ secrets.CREDIMI_API_KEY }}
          apk-url: https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/releases/download/Wallet%2FDemo_Version%3D2026.02.35-Demo_Build%3D35/2026.02.35-Demo.apk
          pipeline-ids: |
            forkbomb-bv-andrea/eudiw-12-34-webuild-conformance-check
            forkbomb-bv-andrea/eudiw-2026-02-35-get-pid-sd-jwt-vc-issuer-backend
          runner-types: |
            android_emulator
            redroid
          extra-runs: |
            forkbomb-bv-andrea/eudiw-2026-02-35-pid-issue-x2-and-verify-x1-issuer-eudiw-dev-test1 forkbomb-bv-andrea/pixel-android16-a2/android_phone
          exclude-runs: |
            forkbomb-bv-andrea/eudiw-12-34-webuild-conformance-check android_emulator
      - name: 🪪 Run the issuer pipeline
        uses: ./
        with:
          api-key: ${{ secrets.CREDIMI_API_KEY }}
          issuer-url: https://backend.issuer.eudiw.dev/credential_offer_create
          credential-ids: |
            forkbomb-bv-andrea/misc-issuer-integration-demo/eudiw-pid-pid-vc-sd-jwt-haip-vci
            forkbomb-bv-andrea/misc-issuer-integration-demo/eudiw-pid-mdoc-haip-vci
          pipeline-ids: |
            forkbomb-bv-andrea/test-openidvci-issuer-1
